#Requires -Version 5.1
<#
.SYNOPSIS
    Bootstrap script for Machine Sync on Windows

.DESCRIPTION
    Sets up a new Windows machine to join the sync ecosystem:
    1. Detects machine hardware
    2. Registers in machines/registry.yaml
    3. Creates machine-specific directory
    4. Installs sync daemon (Task Scheduler)
    5. Deploys configs

.EXAMPLE
    .\bootstrap.ps1
    .\bootstrap.ps1 -MachineName "my-pc"
#>

param(
    [string]$MachineName,
    [switch]$SkipDaemon,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$RepoPath = Split-Path -Parent $MyInvocation.MyCommand.Path

# Colors
function Write-Step { param($msg) Write-Host "`n[>] $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "    [OK] $msg" -ForegroundColor Green }
function Write-Warning { param($msg) Write-Host "    [!] $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "    [X] $msg" -ForegroundColor Red }
function Write-Info { param($msg) Write-Host "    $msg" -ForegroundColor Gray }

# Banner
Write-Host @"

  ╔═══════════════════════════════════════════════════════════╗
  ║       Machine Sync Bootstrap - Windows                    ║
  ╚═══════════════════════════════════════════════════════════╝

"@ -ForegroundColor Magenta

# Step 1: Detect Hardware
Write-Step "Detecting hardware..."

$hostname = $env:COMPUTERNAME
$cs = Get-CimInstance Win32_ComputerSystem
$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$gpu = Get-CimInstance Win32_VideoController | Where-Object { $_.Name -notmatch "Microsoft|Basic" } | Select-Object -First 1
$os = Get-CimInstance Win32_OperatingSystem

Write-Success "Hostname: $hostname"
Write-Success "Model: $($cs.Manufacturer) $($cs.Model)"
Write-Success "CPU: $($cpu.Name)"
Write-Success "GPU: $($gpu.Name)"
Write-Success "OS: $($os.Caption)"

# Generate machine ID from hostname
if (-not $MachineName) {
    $MachineName = $hostname.ToLower() -replace '[^a-z0-9]', '-'
}
Write-Info "Machine ID: $MachineName"

# Step 2: Check/Create Machine Entry
Write-Step "Checking machine registry..."

$registryPath = "$RepoPath\machines\registry.yaml"
$machineDir = "$RepoPath\machines\$MachineName"

# Check if already registered
$registryContent = Get-Content $registryPath -Raw -ErrorAction SilentlyContinue
if ($registryContent -and $registryContent -match "^\s+$($MachineName):" -and -not $Force) {
    Write-Success "Machine '$MachineName' already registered"
}
else {
    Write-Info "Adding machine to registry..."

    # Create machine entry YAML
    $machineEntry = @"

  $MachineName`:
    hostname: $hostname
    platform: windows
    os: $($os.Caption)
    hardware:
      vendor: $($cs.Manufacturer)
      model: $($cs.Model)
      type: $(if ($cs.Model -match "Laptop|Notebook") { "laptop" } else { "desktop" })
      cpu: $($cpu.Name)
      gpu: $($gpu.Name)
    status: active
    primary_user: $env:USERNAME
    config_paths:
      home: "$($env:USERPROFILE -replace '\\', '\\\\')"
      claude: "$($env:USERPROFILE -replace '\\', '\\\\')\\.claude"
      sync_repo: "$($RepoPath -replace '\\', '\\\\')"
"@

    # Append to registry (before platforms: section)
    $registryContent = $registryContent -replace "(platforms:)", "$machineEntry`n`n`$1"
    $registryContent | Set-Content $registryPath -NoNewline

    # Also add to platforms.windows.machines list
    if ($registryContent -match "windows:\s*\n\s*machines:\s*\n(\s*-[^\n]+\n)*") {
        # Add machine to list
        $registryContent = Get-Content $registryPath -Raw
        $registryContent = $registryContent -replace "(windows:\s*\n\s*machines:\s*\n)", "`$1      - $MachineName`n"
        $registryContent | Set-Content $registryPath -NoNewline
    }

    Write-Success "Machine registered"
}

# Step 3: Create Machine Directory
Write-Step "Setting up machine directory..."

if (-not (Test-Path $machineDir)) {
    New-Item -ItemType Directory -Path $machineDir -Force | Out-Null
    New-Item -ItemType Directory -Path "$machineDir\claude" -Force | Out-Null
    New-Item -ItemType Directory -Path "$machineDir\shell" -Force | Out-Null
    Write-Success "Created $machineDir"
}

# Create machine.yaml
$machineYaml = @"
# Machine: $($cs.Model)
# Auto-generated by bootstrap.ps1 on $(Get-Date -Format "yyyy-MM-dd")

machine:
  name: $($cs.Model)
  hostname: $hostname
  id: $MachineName
  type: $(if ($cs.Model -match "Laptop|Notebook") { "laptop" } else { "desktop" })

hardware:
  vendor: $($cs.Manufacturer)
  model: $($cs.Model)
  chassis: $(if ($cs.Model -match "Laptop|Notebook") { "laptop" } else { "desktop" })

  cpu:
    model: $($cpu.Name)
    cores: $($cpu.NumberOfCores)
    threads: $($cpu.NumberOfLogicalProcessors)
    architecture: $($cpu.AddressWidth)-bit

  gpu:
    model: $($gpu.Name)
    driver: $($gpu.DriverVersion)

  memory:
    total: $([math]::Round($cs.TotalPhysicalMemory / 1GB))GB

os:
  name: $($os.Caption)
  version: $($os.Version)
  shell: PowerShell

software:
  claude_code: $(claude --version 2>$null | Select-Object -First 1)
  git: $(git --version 2>$null)

sync_config:
  daemon_type: task_scheduler
  task_name: Machine-Sync-Daemon
  sync_interval_minutes: 5

last_updated: $(Get-Date -Format "yyyy-MM-dd")
"@

$machineYaml | Set-Content "$machineDir\machine.yaml"
Write-Success "Created machine.yaml"

# Step 4: Install Sync Daemon
if (-not $SkipDaemon) {
    Write-Step "Installing sync daemon..."

    $daemonScript = "$RepoPath\platform\windows\scripts\sync-daemon.ps1"
    if (Test-Path $daemonScript) {
        & $daemonScript -Mode Install
        Write-Success "Sync daemon installed"
    }
    else {
        Write-Warning "Daemon script not found at $daemonScript"
    }
}

# Step 5: Deploy Configs
Write-Step "Deploying configurations..."

# Copy universal Claude settings
$universalSettings = "$RepoPath\universal\claude\settings.json"
$claudeDir = "$env:USERPROFILE\.claude"

if (-not (Test-Path $claudeDir)) {
    New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
}

if (Test-Path $universalSettings) {
    Copy-Item $universalSettings "$claudeDir\settings.json" -Force
    Write-Success "Deployed Claude settings"
}

# Copy machine-specific settings if exists
$machineSettings = "$machineDir\claude\settings.local.json"
if (Test-Path $machineSettings) {
    Copy-Item $machineSettings "$claudeDir\settings.local.json" -Force
    Write-Success "Deployed machine-specific settings"
}

# Step 6: Commit and Push
Write-Step "Committing registration..."

Push-Location $RepoPath
try {
    git add machines/
    $hasChanges = git status --porcelain | Where-Object { $_ -match "^[AM]" }
    if ($hasChanges) {
        git commit -m "[machine:$MachineName] Register new machine: $hostname

Hardware: $($cs.Manufacturer) $($cs.Model)
OS: $($os.Caption)
User: $env:USERNAME

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

        git push
        Write-Success "Registration pushed to remote"
    }
    else {
        Write-Info "No changes to commit"
    }
}
catch {
    Write-Warning "Could not push: $_"
}
finally {
    Pop-Location
}

# Done
Write-Host @"

  ╔═══════════════════════════════════════════════════════════╗
  ║                  Bootstrap Complete!                      ║
  ╚═══════════════════════════════════════════════════════════╝

"@ -ForegroundColor Green

Write-Host "  Machine: $MachineName" -ForegroundColor White
Write-Host "  Config:  $machineDir" -ForegroundColor White
Write-Host "  Daemon:  $(if ($SkipDaemon) { 'Skipped' } else { 'Installed' })" -ForegroundColor White
Write-Host ""
Write-Host "  Sync will happen automatically every 5 minutes." -ForegroundColor Cyan
Write-Host "  Manual sync: .\platform\windows\scripts\sync-daemon.ps1 -Mode SyncNow" -ForegroundColor Cyan
Write-Host ""
