#!/bin/bash
# Bootstrap script for Machine Sync on Linux
#
# Sets up a new Linux machine to join the sync ecosystem:
# 1. Detects machine hardware
# 2. Registers in machines/registry.yaml
# 3. Creates machine-specific directory
# 4. Installs sync daemon (systemd)
# 5. Deploys configs
#
# Usage:
#   ./bootstrap.sh
#   ./bootstrap.sh --machine-name my-laptop
#   ./bootstrap.sh --skip-daemon

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

step() { echo -e "\n${CYAN}[>] $1${NC}"; }
success() { echo -e "    ${GREEN}[OK]${NC} $1"; }
warn() { echo -e "    ${YELLOW}[!]${NC} $1"; }
error() { echo -e "    ${RED}[X]${NC} $1"; }
info() { echo -e "    ${NC}$1"; }

# Parse arguments
MACHINE_NAME=""
SKIP_DAEMON=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --machine-name)
            MACHINE_NAME="$2"
            shift 2
            ;;
        --skip-daemon)
            SKIP_DAEMON=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --machine-name NAME    Set machine ID (default: derived from hostname)"
            echo "  --skip-daemon          Don't install systemd service"
            echo "  --help                 Show this help"
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Banner
echo -e "${MAGENTA}"
echo "  ╔═══════════════════════════════════════════════════════════╗"
echo "  ║       Machine Sync Bootstrap - Linux                      ║"
echo "  ╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Step 1: Detect Hardware
step "Detecting hardware..."

HOSTNAME=$(hostname)

# Try to get hardware info
VENDOR=$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null || echo "Unknown")
MODEL=$(cat /sys/class/dmi/id/product_name 2>/dev/null || echo "Unknown")
CHASSIS=$(cat /sys/class/dmi/id/chassis_type 2>/dev/null || echo "0")

# Map chassis type
case "$CHASSIS" in
    9|10|14) CHASSIS_TYPE="laptop" ;;
    3|4|5|6|7) CHASSIS_TYPE="desktop" ;;
    *) CHASSIS_TYPE="unknown" ;;
esac

CPU=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
CPU_CORES=$(nproc)

# GPU detection
GPU=$(lspci 2>/dev/null | grep -i "vga\|3d\|display" | head -1 | sed 's/.*: //' || echo "Unknown")

# Memory
MEM_GB=$(free -g | awk '/^Mem:/{print $2}')

# OS
OS_NAME=$(grep -E "^PRETTY_NAME=" /etc/os-release 2>/dev/null | cut -d'"' -f2 || echo "Linux")
DESKTOP=${XDG_CURRENT_DESKTOP:-${DESKTOP_SESSION:-unknown}}

success "Hostname: $HOSTNAME"
success "Model: $VENDOR $MODEL"
success "CPU: $CPU ($CPU_CORES cores)"
success "GPU: $GPU"
success "Memory: ${MEM_GB}GB"
success "OS: $OS_NAME"
success "Desktop: $DESKTOP"

# Generate machine ID
if [ -z "$MACHINE_NAME" ]; then
    MACHINE_NAME=$(echo "$HOSTNAME" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-' | sed 's/-$//')
fi
info "Machine ID: $MACHINE_NAME"

# Step 2: Check/Create Machine Entry
step "Checking machine registry..."

REGISTRY_PATH="$REPO_DIR/machines/registry.yaml"
MACHINE_DIR="$REPO_DIR/machines/$MACHINE_NAME"

# Check if already registered
if grep -q "^  $MACHINE_NAME:" "$REGISTRY_PATH" 2>/dev/null; then
    success "Machine '$MACHINE_NAME' already registered"
else
    info "Adding machine to registry..."

    # Create machine entry
    MACHINE_ENTRY="
  $MACHINE_NAME:
    hostname: $HOSTNAME
    platform: linux
    os: $OS_NAME
    desktop: $DESKTOP
    hardware:
      vendor: $VENDOR
      model: $MODEL
      type: $CHASSIS_TYPE
      cpu: $CPU
      gpu: $GPU
    status: active
    primary_user: $USER
    config_paths:
      home: \"$HOME\"
      claude: \"$HOME/.claude\"
      sync_repo: \"$REPO_DIR\"
      hypr: \"$HOME/.config/hypr\""

    # Insert before platforms: section
    sed -i "/^platforms:/i\\$MACHINE_ENTRY" "$REGISTRY_PATH"

    # Add to platforms.linux.machines list
    sed -i "/linux:/,/machines:/{/machines:/a\\      - $MACHINE_NAME
}" "$REGISTRY_PATH"

    success "Machine registered"
fi

# Step 3: Create Machine Directory
step "Setting up machine directory..."

mkdir -p "$MACHINE_DIR/claude" "$MACHINE_DIR/hypr"

# Create machine.yaml
cat > "$MACHINE_DIR/machine.yaml" << EOF
# Machine: $MODEL
# Auto-generated by bootstrap.sh on $(date +%Y-%m-%d)

machine:
  name: $MODEL
  hostname: $HOSTNAME
  id: $MACHINE_NAME
  type: $CHASSIS_TYPE

hardware:
  vendor: $VENDOR
  model: $MODEL
  chassis: $CHASSIS_TYPE

  cpu:
    model: $CPU
    cores: $CPU_CORES
    architecture: $(uname -m)

  gpu:
    model: $GPU

  memory:
    total: ${MEM_GB}GB

os:
  name: $OS_NAME
  desktop: $DESKTOP
  shell: $SHELL

software:
  claude_code: $(claude --version 2>/dev/null | head -1 || echo "not installed")
  git: $(git --version 2>/dev/null || echo "not installed")

sync_config:
  daemon_type: systemd
  service_name: machine-sync
  sync_interval_minutes: 5

last_updated: $(date +%Y-%m-%d)
EOF

success "Created machine.yaml"

# Step 4: Install Sync Daemon
if [ "$SKIP_DAEMON" = false ]; then
    step "Installing sync daemon..."

    DAEMON_SCRIPT="$REPO_DIR/platform/linux/scripts/sync-daemon.sh"
    if [ -f "$DAEMON_SCRIPT" ]; then
        chmod +x "$DAEMON_SCRIPT"
        "$DAEMON_SCRIPT" --install
        success "Sync daemon installed"
    else
        warn "Daemon script not found at $DAEMON_SCRIPT"
    fi
fi

# Step 5: Deploy Configs
step "Deploying configurations..."

# Copy universal Claude settings
UNIVERSAL_SETTINGS="$REPO_DIR/universal/claude/settings.json"
CLAUDE_DIR="$HOME/.claude"

mkdir -p "$CLAUDE_DIR"

if [ -f "$UNIVERSAL_SETTINGS" ]; then
    cp "$UNIVERSAL_SETTINGS" "$CLAUDE_DIR/settings.json"
    success "Deployed Claude settings"
fi

# Copy machine-specific settings if exists
MACHINE_SETTINGS="$MACHINE_DIR/claude/settings.local.json"
if [ -f "$MACHINE_SETTINGS" ]; then
    cp "$MACHINE_SETTINGS" "$CLAUDE_DIR/settings.local.json"
    success "Deployed machine-specific settings"
fi

# Deploy omarchy configs if this is a Linux+Hyprland machine
if [ -d "$HOME/.config/hypr" ] && [ -d "$REPO_DIR/platform/linux/omarchy" ]; then
    info "Hyprland detected, deploying omarchy configs..."

    # Deploy universal omarchy
    if [ -d "$REPO_DIR/platform/linux/omarchy/hypr" ]; then
        cp -r "$REPO_DIR/platform/linux/omarchy/hypr/"* "$HOME/.config/hypr/" 2>/dev/null || true
        success "Deployed universal Hyprland configs"
    fi

    # Deploy machine-specific
    if [ -d "$MACHINE_DIR/hypr" ]; then
        cp -r "$MACHINE_DIR/hypr/"* "$HOME/.config/hypr/" 2>/dev/null || true
        success "Deployed machine-specific Hyprland configs"
    fi
fi

# Step 6: Commit and Push
step "Committing registration..."

cd "$REPO_DIR"
git add machines/
if git diff --cached --quiet; then
    info "No changes to commit"
else
    git commit -m "[machine:$MACHINE_NAME] Register new machine: $HOSTNAME

Hardware: $VENDOR $MODEL
OS: $OS_NAME
Desktop: $DESKTOP
User: $USER

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

    if git push 2>/dev/null; then
        success "Registration pushed to remote"
    else
        warn "Could not push (check network/auth)"
    fi
fi

# Done
echo -e "${GREEN}"
echo "  ╔═══════════════════════════════════════════════════════════╗"
echo "  ║                  Bootstrap Complete!                      ║"
echo "  ╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo "  Machine: $MACHINE_NAME"
echo "  Config:  $MACHINE_DIR"
echo "  Daemon:  $(if $SKIP_DAEMON; then echo 'Skipped'; else echo 'Installed'; fi)"
echo ""
echo -e "  ${CYAN}Sync will happen automatically every 5 minutes.${NC}"
echo -e "  ${CYAN}Manual sync: ./platform/linux/scripts/sync-daemon.sh --status${NC}"
echo ""
