#!/bin/bash
# Omarchy Config Deployment Script
# Deploys universal + machine-specific configs to ~/.config/

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTNAME=$(hostname)
CONFIG_DIR="$HOME/.config"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Omarchy Config Deployment                ║${NC}"
echo -e "${BLUE}║   Machine: ${GREEN}$HOSTNAME${BLUE}                       ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"

# Check if machine-specific config exists
if [ ! -d "$SCRIPT_DIR/machines/$HOSTNAME" ]; then
    echo -e "${YELLOW}⚠ No machine-specific config found for '$HOSTNAME'${NC}"
    echo -e "${YELLOW}  Creating template at: machines/$HOSTNAME/${NC}"
    mkdir -p "$SCRIPT_DIR/machines/$HOSTNAME/hypr"
    echo "# $HOSTNAME Hyprland config - customize for this machine" > "$SCRIPT_DIR/machines/$HOSTNAME/hypr/README.md"
    echo -e "${YELLOW}  Please configure machines/$HOSTNAME/ before deploying${NC}"
    exit 1
fi

# Backup function
backup_file() {
    local file="$1"
    if [ -f "$file" ] && [ ! -L "$file" ]; then
        local backup="${file}.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$file" "$backup"
        echo -e "  ${YELLOW}↳ Backed up: ${backup}${NC}"
    fi
}

# Deploy function - copies file if different
deploy_file() {
    local src="$1"
    local dest="$2"
    local name="$3"

    if [ -f "$src" ]; then
        mkdir -p "$(dirname "$dest")"
        if [ -f "$dest" ] && cmp -s "$src" "$dest"; then
            echo -e "  ${GREEN}✓${NC} $name (unchanged)"
        else
            backup_file "$dest"
            cp "$src" "$dest"
            echo -e "  ${GREEN}✓${NC} $name ${BLUE}(updated)${NC}"
        fi
    fi
}

# Deploy directory contents
deploy_dir() {
    local src_dir="$1"
    local dest_dir="$2"
    local name="$3"

    if [ -d "$src_dir" ]; then
        mkdir -p "$dest_dir"
        for file in "$src_dir"/*; do
            if [ -f "$file" ]; then
                local filename=$(basename "$file")
                deploy_file "$file" "$dest_dir/$filename" "$name/$filename"
            fi
        done
    fi
}

echo ""
echo -e "${GREEN}► Deploying UNIVERSAL configs...${NC}"

# Hyprland universal configs
deploy_file "$SCRIPT_DIR/universal/hypr/bindings.conf" "$CONFIG_DIR/hypr/bindings-universal.conf" "hypr/bindings-universal.conf"
deploy_file "$SCRIPT_DIR/universal/hypr/envs.conf" "$CONFIG_DIR/hypr/envs.conf" "hypr/envs.conf"
deploy_file "$SCRIPT_DIR/universal/hypr/workspace-window-rules.conf" "$CONFIG_DIR/hypr/workspace-window-rules.conf" "hypr/workspace-window-rules.conf"
deploy_file "$SCRIPT_DIR/universal/hypr/apps.conf" "$CONFIG_DIR/hypr/apps.conf" "hypr/apps.conf"
deploy_dir "$SCRIPT_DIR/universal/hypr/apps" "$CONFIG_DIR/hypr/apps" "hypr/apps"

# Waybar
deploy_file "$SCRIPT_DIR/universal/waybar/config.jsonc" "$CONFIG_DIR/waybar/config.jsonc" "waybar/config.jsonc"
deploy_file "$SCRIPT_DIR/universal/waybar/style.css" "$CONFIG_DIR/waybar/style.css" "waybar/style.css"

# Terminals
deploy_file "$SCRIPT_DIR/universal/terminals/alacritty.toml" "$CONFIG_DIR/alacritty/alacritty.toml" "alacritty/alacritty.toml"
deploy_file "$SCRIPT_DIR/universal/terminals/kitty.conf" "$CONFIG_DIR/kitty/kitty.conf" "kitty/kitty.conf"
deploy_file "$SCRIPT_DIR/universal/terminals/ghostty.conf" "$CONFIG_DIR/ghostty/config" "ghostty/config"

# Walker
deploy_file "$SCRIPT_DIR/universal/walker/config.toml" "$CONFIG_DIR/walker/config.toml" "walker/config.toml"

echo ""
echo -e "${GREEN}► Deploying MACHINE-SPECIFIC configs for ${YELLOW}$HOSTNAME${GREEN}...${NC}"

# Hyprland machine-specific configs (these override universal where applicable)
MACHINE_DIR="$SCRIPT_DIR/machines/$HOSTNAME"

deploy_file "$MACHINE_DIR/hypr/monitors.conf" "$CONFIG_DIR/hypr/monitors.conf" "hypr/monitors.conf"
deploy_file "$MACHINE_DIR/hypr/input.conf" "$CONFIG_DIR/hypr/input.conf" "hypr/input.conf"
deploy_file "$MACHINE_DIR/hypr/looknfeel.conf" "$CONFIG_DIR/hypr/looknfeel.conf" "hypr/looknfeel.conf"
deploy_file "$MACHINE_DIR/hypr/bindings.conf" "$CONFIG_DIR/hypr/bindings-machine.conf" "hypr/bindings-machine.conf"

# Create combined bindings.conf that sources both universal and machine-specific
COMBINED_BINDINGS="$CONFIG_DIR/hypr/bindings.conf"
cat > "$COMBINED_BINDINGS" << 'EOF'
# Combined bindings - auto-generated by deploy.sh
# DO NOT EDIT - changes will be overwritten!
# Edit the source files in claude-cross-machine-sync/omarchy/ instead

# Universal bindings (work on any machine)
source = ~/.config/hypr/bindings-universal.conf

# Machine-specific bindings (only for this machine)
source = ~/.config/hypr/bindings-machine.conf
EOF
echo -e "  ${GREEN}✓${NC} hypr/bindings.conf ${BLUE}(combined)${NC}"

echo ""
echo -e "${GREEN}► Deployment complete!${NC}"
echo ""
echo -e "${YELLOW}To apply changes:${NC}"
echo -e "  ${BLUE}hyprctl reload${NC}        - Reload Hyprland config"
echo -e "  ${BLUE}pkill waybar && waybar &${NC} - Restart Waybar"
echo ""
echo -e "${YELLOW}Config sources:${NC}"
echo -e "  Universal:  ${BLUE}$SCRIPT_DIR/universal/${NC}"
echo -e "  Machine:    ${BLUE}$MACHINE_DIR/${NC}"
