# Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrulev2 = tag +jetbrains-splash, class:^(jetbrains-.*)$, title:^(splash)$, floating:1
windowrulev2 = center, tag:jetbrains-splash
windowrulev2 = nofocus, tag:jetbrains-splash
windowrulev2 = noborder, tag:jetbrains-splash

# Center popups/find windows
windowrulev2 = tag +jetbrains, class:^(jetbrains-.*), title:^()$, floating:1
windowrulev2 = center, tag:jetbrains

# Enabling this makes it possible to provide input in popup dialogs (search window, new file, etc.)
windowrulev2 = stayfocused, tag:jetbrains
windowrulev2 = noborder, tag:jetbrains

# For some reason tag:jetbrains does not work for size rule
windowrulev2 = size >50% >50%, class:^(jetbrains-.*), title:^()$, floating:1

# Disable window flicker when autocomplete or tooltips appear
windowrulev2 = noinitialfocus, class:^(jetbrains-.*)$, title:^(win.*)$, floating:1

# Disable mouse focus
windowrulev2 = nofollowmouse, class:^(jetbrains-.*)$