# Stability / Architecture
--ozone-platform=x11
# --ozone-platform=wayland
--enable-wayland-ime

# Display / UI
--force-device-scale-factor=0.75
--autoplay-policy=no-user-gesture-required

# Performance (Speed)
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization,ParallelDownloading,BackForwardCache:enable_same_site/true

# Networking
--enable-quic

# Edgy / Experimental Features
--enable-experimental-web-platform-features
--allow-running-insecure-content
